### ISSUE TITLE
FYI I have a working interpreter of Skylark in rust

### ISSUE THREAD

**Issue by damienmg** [luser/rust-skylark#1]
I am going through the open sourcing of it, it should be OSS in the next weeks.

**Comment by luser** [comment]
Oh, awesome! I'd love to see it! Thanks for the info!

**Comment by laurentlb** [comment]
And for the record, we've renamed Skylark into Starlark ([announcement on Bazel blog](https://blog.bazel.build/2018/08/17/starlark.html))
Official repo: https://github.com/bazelbuild/starlark
(the Go implementation will be renamed too)

**Comment by damienmg** [comment]
Hi @luser, I finally got all the approval and published it: https://crates.io/crates/starlark (https://github.com/google/starlark) :)

**Comment by laurentlb** [comment]
Typo - address is: https://github.com/google/starlark-rust

**Comment by luser** [comment]
Awesome, thanks for the info!
